import {db,user} from '@/lib/server';
import {cors,preflight} from '@/lib/cors';
import {z} from 'zod';
const schema=z.object({variant_id:z.string().min(1).max(200),quantity:z.number().int().min(0).max(100)});
type Line={variant_id:string;quantity:number};
type CartVariant={id:string;is_available:boolean;launch_blockers:string[];products:{is_active:boolean;is_seasonal:boolean}};
async function lines(userId:string){return await db<Line[]>('cart_items?user_id=eq.'+userId+'&select=variant_id,quantity&order=updated_at');}
export async function OPTIONS(r:Request){return preflight(r);}
export async function GET(r:Request){try{const u=await user(r);return cors(r,Response.json(await lines(u.id)));}catch(e){return cors(r,Response.json({error:(e as Error).message},{status:401}));}}
export async function PUT(r:Request){let u;try{u=await user(r);}catch(e){return cors(r,Response.json({error:(e as Error).message},{status:401}));}try{const data=schema.parse(await r.json());if(data.quantity===0){await db('cart_items?user_id=eq.'+u.id+'&variant_id=eq.'+data.variant_id,{method:'DELETE'});return cors(r,Response.json(await lines(u.id)));}const [v]=await db<CartVariant[]>('product_variants?select=id,is_available,launch_blockers,products!inner(is_active,is_seasonal)&id=eq.'+data.variant_id);if(!v||!v.is_available||v.launch_blockers.length||!v.products.is_active||v.products.is_seasonal)throw new Error('An item is unavailable. Please review your bag.');await db('cart_items',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify({user_id:u.id,variant_id:data.variant_id,quantity:data.quantity,updated_at:new Date().toISOString()})});return cors(r,Response.json(await lines(u.id)));}catch(e){return cors(r,Response.json({error:e instanceof z.ZodError?'Please check the item and quantity.':(e as Error).message},{status:400}));}}
export async function DELETE(r:Request){try{const u=await user(r);const variant=new URL(r.url).searchParams.get('variant_id');await db('cart_items?user_id=eq.'+u.id+(variant?'&variant_id=eq.'+variant:''),{method:'DELETE'});return cors(r,Response.json(await lines(u.id)));}catch(e){return cors(r,Response.json({error:(e as Error).message},{status:401}));}}
