'use client';
import {useEffect,useState} from 'react';
import {BRAND,TAGLINE,collections,demoCatalog,money,normalizeCatalog,type Variant} from '@/lib/catalog';
import {subscribeTableChanges} from '@/lib/realtime';
type Line={variant_id:string;quantity:number};
type Order={error?:string;id:string;reference:string;payment_status:string;approval_status:string;fulfilment_status:string|null;total_minor:number;currency:string;pickup_at:string;email_status?:string;items?:{name:string;option:string;quantity:number;sell_unit:string;pieces_per_unit:number|null;preset_contents:string[]}[];order_items?:{name:string;option:string;quantity:number;sell_unit:string;pieces_per_unit:number|null;preset_contents:string[]}[]};
export default function Shop(){
 const [profile,setProfile]=useState({name:'',email:'',phone:''});
 const [page,setPage]=useState('home'),[catalog,setCatalog]=useState<Variant[]>(normalizeCatalog(demoCatalog)),[connected,setConnected]=useState(false),[collection,setCollection]=useState('All bakes'),[selected,setSelected]=useState<Variant|null>(null),[cart,setCart]=useState<Line[]>([]),[ready,setReady]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[token,setToken]=useState(''),[orders,setOrders]=useState<Order[]>([]),[order,setOrder]=useState<Order|null>(null),[cfg,setCfg]=useState<{url:string;key:string}|null>(null);
 useEffect(()=>{queueMicrotask(()=>{try{setCart(JSON.parse(localStorage.getItem('gracie-bag')||'[]'));setToken(sessionStorage.getItem('gracie-token')||'');}catch{}setReady(true);fetch('/api/catalog').then(r=>r.json() as Promise<{variants:Variant[];connected:boolean}>).then(d=>{setCatalog(d.variants);setConnected(d.connected)}).catch(()=>setMessage('Showing the demo menu. Database connection is pending.'));const url=new URL(location.href);const code=url.searchParams.get('code');if(code){const verifier=sessionStorage.getItem('gracie-verifier');fetch('/api/config').then(r=>r.json() as Promise<{url:string;key:string}>).then(async c=>{const r=await fetch(c.url+'/auth/v1/token?grant_type=pkce',{method:'POST',headers:{apikey:c.key,'Content-Type':'application/json'},body:JSON.stringify({auth_code:code,code_verifier:verifier})});const d=await r.json() as {access_token:string};if(!r.ok)throw new Error('Sign-in could not finish. Please try again.');sessionStorage.setItem('gracie-token',d.access_token);setToken(d.access_token);setPage('checkout');history.replaceState({},'',location.pathname);}).catch(e=>setMessage(e.message));}if(url.searchParams.get('error'))setMessage('Google sign-in was cancelled or failed. Your bag is still saved.');});},[]);
 useEffect(()=>{if(ready&&!token)localStorage.setItem('gracie-bag',JSON.stringify(cart));},[cart,ready,token]);
 useEffect(()=>{if(token)fetch('/api/profile',{headers:{Authorization:'Bearer '+token}}).then(r=>r.json() as Promise<{name:string;email:string;phone:string}>).then(p=>setProfile(p)).catch(()=>{});},[token]);
 const items=cart.map(l=>({...l,v:catalog.find(v=>v.id===l.variant_id)})).filter(l=>l.v);
 const total=items.reduce((sum,l)=>sum+l.v!.price_minor*l.quantity,0),count=cart.reduce((s,l)=>s+l.quantity,0);
 const sameProduct=(a:Variant,b:Variant)=>a.collection===b.collection&&a.name===b.name;
 const products=catalog.filter((v,i,a)=>a.findIndex(x=>sameProduct(x,v)&&(!x.launch_blockers.length||!a.some(y=>sameProduct(y,v)&&!y.launch_blockers.length)))===i&&(collection==='All bakes'||v.collection===collection));
 const variantsOf=(v:Variant)=>catalog.filter(x=>sameProduct(x,v));
 const minPrice=(v:Variant)=>Math.min(...variantsOf(v).map(x=>x.price_minor));
 const optionCount=(v:Variant)=>variantsOf(v).length;
 function navigate(p:string){setPage(p);setSelected(null);setMessage('');window.scrollTo({top:0,behavior:'smooth'});if(p==='orders'&&token)loadOrders();}
 async function loadOrders(){try{const r=await fetch('/api/orders',{headers:{Authorization:'Bearer '+token}});const d=await r.json() as Order[] & {error?:string};if(!r.ok)throw new Error(d.error);setOrders(d);}catch(e){setMessage((e as Error).message);}}
 async function fetchCart(){const r=await fetch('/api/cart',{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw new Error('bag');return await r.json() as Line[];}
 async function loadCart(){try{setCart(await fetchCart());}catch{}}
 async function saveLine(variant_id:string,quantity:number){try{const r=await fetch('/api/cart',{method:'PUT',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({variant_id,quantity})});if(!r.ok){const d=await r.json() as {error?:string};setMessage(d.error||'Could not update your saved bag.');}}catch{setMessage('Could not reach your saved bag. This device copy is kept.');}}
 async function dropLine(variant_id:string){try{await fetch('/api/cart?variant_id='+encodeURIComponent(variant_id),{method:'DELETE',headers:{Authorization:'Bearer '+token}});}catch{}}
 async function clearServerCart(){try{await fetch('/api/cart',{method:'DELETE',headers:{Authorization:'Bearer '+token}});}catch{}}
 useEffect(()=>{if(!token)return;let cancelled=false,stop:(()=>void)|null=null;(async()=>{try{const fetched=await fetch('/api/config').then(r=>r.json() as Promise<{url:string;key:string}>);const c=cfg&&cfg.url&&cfg.key?cfg:fetched;if(cancelled||!c.url||!c.key)return;setCfg(c);let local:Line[]=[];try{local=JSON.parse(localStorage.getItem('gracie-bag')||'[]');}catch{local=[];}const server=await fetchCart();if(cancelled)return;setCart(server);for(const l of local){const s=server.find(x=>x.variant_id===l.variant_id);await saveLine(l.variant_id,Math.min(100,(s?.quantity||0)+l.quantity));}if(local.length){localStorage.removeItem('gracie-bag');const merged=await fetchCart();if(!cancelled)setCart(merged);}stop=subscribeTableChanges({url:c.url,key:c.key,token,onChange:()=>{if(!cancelled)loadCart();}});}catch{}})();return()=>{cancelled=true;if(stop)stop();};},[token]);
 async function login(){setBusy(true);try{const c=await fetch('/api/config').then(r=>r.json() as Promise<{url:string;key:string}>);if(!c.url||!c.key)throw new Error('Google sign-in is not connected yet. The owner must complete the account setup. Your bag is saved.');const bytes=crypto.getRandomValues(new Uint8Array(32));const verifier=btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=/g,'');const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));const challenge=btoa(String.fromCharCode(...new Uint8Array(hash))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=/g,'');sessionStorage.setItem('gracie-verifier',verifier);const u=new URL(c.url+'/auth/v1/authorize');u.searchParams.set('provider','google');u.searchParams.set('redirect_to',location.origin+'/');u.searchParams.set('scopes','openid email profile');u.searchParams.set('code_challenge',challenge);u.searchParams.set('code_challenge_method','s256');location.assign(u);}catch(e){setMessage((e as Error).message);setBusy(false);}}
 function add(v:Variant){const next=Math.min(100,(cart.find(l=>l.variant_id===v.id)?.quantity||0)+1);setCart(c=>c.some(l=>l.variant_id===v.id)?c.map(l=>l.variant_id===v.id?{...l,quantity:Math.min(100,l.quantity+1)}:l):[...c,{variant_id:v.id,quantity:1}]);if(token)saveLine(v.id,next);sessionStorage.removeItem('gracie-checkout-key');setMessage(v.name+' added to your bag.');}
 async function checkout(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f=new FormData(e.currentTarget);const pickup=new Date(String(f.get('pickup')));if(isNaN(pickup.getTime()))throw new Error('Choose your pickup date and time.');const fingerprint=JSON.stringify([cart,...f.entries()]);let key=sessionStorage.getItem('gracie-checkout-key');if(!key||sessionStorage.getItem('gracie-checkout-fingerprint')!==fingerprint){key=crypto.randomUUID();sessionStorage.setItem('gracie-checkout-key',key);sessionStorage.setItem('gracie-checkout-fingerprint',fingerprint);}const r=await fetch('/api/orders',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({name:f.get('name'),email:f.get('email'),phone:f.get('phone'),pickup_at:pickup.toISOString(),notes:f.get('notes'),bulk:f.get('bulk')==='on',lines:cart,idempotency_key:key})});const d=await r.json() as Order;if(!r.ok)throw new Error(d.error);setOrder(d);setPage('order');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function pay(){if(!order)return;setBusy(true);try{const r=await fetch('/api/demo-payment',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({id:order.id})});const d=await r.json() as Order;if(!r.ok)throw new Error(d.error);setOrder(d);setCart([]);if(token)clearServerCart();sessionStorage.removeItem('gracie-checkout-key');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const policy=<p className="policy">Baked to order · Pickup only · At least 24 hours’ notice in demo mode. Urgent and bulk orders need owner approval.</p>;
 const summary=<div className="summary"><h2>Your order</h2>{items.map(l=><div className="summary-line" key={l.variant_id}><span>{l.v!.name}<small>{l.v!.option} · {l.quantity} {l.v!.sell_unit}{l.quantity>1?'s':''}{l.v!.pieces_per_unit?' · '+l.quantity*l.v!.pieces_per_unit+' pieces':''}</small></span><strong>{money(l.v!.price_minor*l.quantity)}</strong></div>)}<div className="summary-line"><span>Subtotal</span><strong>{money(total)}</strong></div><div className="summary-line total"><span>Total</span><strong>{money(total)}</strong></div><small>Demo pricing — not final. No real charges.</small>{policy}</div>;
 return <><div className="topbar">Made to order, made for your moments. <span>Pickup only</span></div><header><button className="brand" onClick={()=>navigate('home')}><span className="brand-mark">g<span>✦</span></span><span>{BRAND}<small>{TAGLINE}</small></span></button><nav aria-label="Main navigation"><button className={page==='shop'?'active':''} onClick={()=>navigate('shop')}>Shop</button><button onClick={()=>navigate('about')}>Our bakery</button><button onClick={()=>navigate('orders')}>My orders</button><button className="bag" onClick={()=>navigate('cart')}>Bag <span>{count}</span></button></nav></header><div className="demo-banner">Demo pricing — not final · No real payments {connected?'':'· Database setup pending'}</div><main>{message&&<div className="message" role="status">{message}<button aria-label="Dismiss message" onClick={()=>setMessage('')}>×</button></div>}
 {page==='home'&&<><section className="hero"><div><p className="eyebrow">THE LITTLE JOYS, FRESHLY BAKED</p><h1>A little sweetness.<br/><em>A lovely moment.</em></h1><p>Cakes, banana bread and bite-sized bakes for everyday treats, thoughtful gifts and sharing around the table.</p><button className="primary" onClick={()=>navigate('shop')}>Explore our bakes</button>{policy}<div className="hero-note"><span>01</span> Choose your favourites<br/><span>02</span> Order ahead & pick up</div></div><figure><img src="/bakery.png" alt="Illustrative chocolate cake slice, banana loaf and muffins on a cream table"/><figcaption>Illustrative image — actual product may vary</figcaption><div className="photo-stamp">Freshly baked.<br/>Worth the wait.</div></figure></section><section className="collections"><div className="section-title"><div><p className="eyebrow">SOMETHING FOR EVERY SWEET TOOTH</p><h2>Find your favourite</h2></div><button onClick={()=>navigate('shop')}>Browse the menu</button></div><div className="collection-grid">{collections.map((c,i)=><button key={c} onClick={()=>{setCollection(c);navigate('shop')}}><span className="collection-number">0{i+1}</span><h3>{c}</h3><p>{['Six flavours, four cake sizes.','Your everyday slice of comfort.','Mini banana loaves and mini cakes to share.','One flavour, six lovely pieces.'][i]}</p><span>Explore collection</span></button>)}</div></section><section className="notice"><h2>Good things take a little time.</h2><p>Every order is baked for you. Please order ahead and collect at an agreed pickup time. Urgent order? Contact us to confirm availability. Bulk orders need additional notice.</p><button className="primary" onClick={()=>navigate('checkout')}>Request an urgent or bulk order</button></section></>}
 {page==='shop'&&!selected&&<section className="shop"><p className="eyebrow">BAKED FOR YOU</p><h1>The bake shop</h1>{policy}<div className="filters" aria-label="Collections">{['All bakes',...collections].map(c=><button className={c===collection?'chosen':''} onClick={()=>setCollection(c)} key={c}>{c}</button>)}</div><div className="product-grid">{products.map(v=>{const varies=new Set(variantsOf(v).map(x=>x.price_minor)).size>1;return <button className="product" key={v.id} onClick={()=>setSelected(v)}><div className="product-art"><img src={v.image_path||"/bakery.png"} alt={v.image_alt||"Illustrative bakery selection"}/><span>{v.collection}</span></div><div className="product-body"><h3>{v.name}</h3><p>{v.launch_blockers.length?'Details coming soon':(varies?'From ':'')+money(minPrice(v))}</p><small>{v.launch_blockers.length?'Unavailable':'Demo pricing — not final'}</small>{v.is_temporary_image!==false&&<small>Illustrative image — actual product may vary</small>}<span className="choose-options">{v.launch_blockers.length?'View details':'Choose options'+(optionCount(v)>1?' · '+optionCount(v)+' available':'')}</span></div></button>;})}</div></section>}
 {page==='shop'&&selected&&<section className="detail"><button onClick={()=>setSelected(null)}>Back to the menu</button><div className="detail-grid"><figure><img src={selected.image_path||"/bakery.png"} alt={selected.image_alt||"Illustrative bakery selection"}/>{selected.is_temporary_image!==false&&<figcaption>Illustrative image — actual product may vary</figcaption>}</figure><div><p className="eyebrow">{selected.collection}</p><h1>{selected.name}</h1><p>Made to order for sharing, gifting or a sweet moment of your own.</p><label>Choose your size or pack<select value={selected.id} onChange={e=>setSelected(catalog.find(v=>v.id===e.target.value)!)}>{catalog.filter(v=>v.name===selected.name&&v.collection===selected.collection).map(v=><option key={v.id} value={v.id}>{v.option}</option>)}</select></label>{selected.preset_contents.length>0&&<p>Preset contents: {selected.preset_contents.join(', ')}</p>}<h2>{money(selected.price_minor)}</h2><p>Demo pricing — not final</p><p>{selected.allergen_text||"Allergen information pending."}{selected.collection==='Banana Bread'?' Dimensions and weights await owner confirmation.':''}</p>{selected.collection==='Foil Cake Packs'&&<p>One flavour per pack of six. Two packs = 12 pieces.</p>}{selected.launch_blockers.length?<p className="unavailable">Unavailable: {selected.launch_blockers.join(', ')}</p>:<button className="primary" onClick={()=>add(selected)}>Add one {selected.sell_unit} to bag</button>}{policy}</div></div></section>}
 {page==='cart'&&<section><p className="eyebrow">YOUR FAVOURITES</p><h1>Your bag</h1>{!items.length?<div className="empty"><h2>A little sweetness awaits.</h2><p>Your bag is empty. Explore the menu to find your first bake.</p><button className="primary" onClick={()=>navigate('shop')}>Shop our bakes</button></div>:<div className="checkout-grid"><div>{items.map(l=><div className="cart-line" key={l.variant_id}><div><h3>{l.v!.name}</h3><p>{l.v!.option}{l.v!.pieces_per_unit?' · '+l.quantity*l.v!.pieces_per_unit+' pieces':''}</p><small>Demo pricing — not final</small></div><label>Quantity ({l.v!.sell_unit}s)<input type="number" min="1" max="100" value={l.quantity} onChange={e=>{const q=Math.max(1,Math.min(100,parseInt(e.target.value)||1));setCart(c=>c.map(x=>x.variant_id===l.variant_id?{...x,quantity:q}:x));if(token)saveLine(l.variant_id,q);}}/></label><button onClick={()=>{setCart(c=>c.filter(x=>x.variant_id!==l.variant_id));if(token)dropLine(l.variant_id);}}>Remove</button></div>)}<button className="primary" onClick={()=>navigate('checkout')}>Continue to checkout</button></div>{summary}</div>}</section>}
 {page==='checkout'&&<section><p className="eyebrow">ONE STEP CLOSER</p><h1>Pickup checkout</h1>{!items.length?<div className="empty"><p>Add a bake to your bag before requesting an order.</p><button className="primary" onClick={()=>navigate('shop')}>Explore the menu</button></div>:<div className="checkout-grid"><div>{!token?<div className="signin"><h2>Sign in to place your order</h2><p>Use Google to keep your order details and pickup progress together. Your bag will stay saved.</p><button className="google" disabled={busy} onClick={login}>G &nbsp; Continue with Google</button><h3 className="checkout-preview">Your pickup details</h3><p>Name, email, phone and requested pickup time are collected after sign-in. No delivery address is needed.</p></div>:<form onSubmit={checkout}><h2>Your details</h2><label>Full name<input name="name" defaultValue={profile.name} autoComplete="name" required minLength={2}/></label><label>Email<input name="email" defaultValue={profile.email} type="email" autoComplete="email" required/></label><label>Phone<input name="phone" defaultValue={profile.phone} type="tel" autoComplete="tel" required minLength={7}/></label><label>Requested pickup (your local time)<input name="pickup" type="datetime-local" required/></label><p>Pickup location and hours are pending owner confirmation. Demo requests do not reserve a real pickup.</p><label>Order notes (optional)<textarea name="notes" maxLength={1000}/></label><label className="checkbox"><input type="checkbox" name="bulk"/> This is an urgent or bulk enquiry</label><p>Requests within 24 hours need approval before demo payment.</p><button className="primary" disabled={busy}>{busy?'Submitting…':'Submit demo order'}</button></form>}</div>{summary}</div>}</section>}
 {page==='order'&&order&&<section className="order"><p className="eyebrow">{order.payment_status==='paid'?'DEMO PAYMENT VERIFIED':'ORDER RECEIVED'}</p><h1>{order.payment_status==='paid'?'Demo order confirmed':order.approval_status==='requested'?'Awaiting owner approval':'Awaiting demo payment'}</h1><p>Reference: <strong>{order.reference}</strong></p>{(order.items||order.order_items||[]).map((i,index)=><div className="summary-line" key={index}><span>{i.name} · {i.option}<small>{i.quantity} {i.sell_unit}(s){i.pieces_per_unit?" · "+i.quantity*i.pieces_per_unit+" pieces":""}</small>{i.preset_contents.length>0&&<small>{i.preset_contents.join(", ")}</small>}</span></div>)}<p>{money(order.total_minor,order.currency)} · Pickup requested: {new Date(order.pickup_at).toLocaleString()}</p><p>Payment: {order.payment_status} · Approval: {order.approval_status} · Progress: {order.fulfilment_status||'Not confirmed'}</p>{order.payment_status==='pending'&&(order.approval_status==='not_required'||order.approval_status==='approved')&&<button className="primary" disabled={busy} onClick={pay}>{busy?'Verifying…':'Simulate demo payment — no charge'}</button>}{order.email_status&&<p>Confirmation email: {order.email_status.replaceAll('_',' ')}</p>}<p>This is a demo order. Pickup details and live payments are pending setup.</p><button onClick={()=>navigate('orders')}>View my orders</button></section>}
 {page==='orders'&&<section><p className="eyebrow">YOUR BAKERY VISITS</p><h1>My orders</h1>{!token?<div className="empty"><p>Sign in with Google to see your order history.</p><button className="google" disabled={busy} onClick={login}>Continue with Google</button></div>:<><button onClick={()=>{sessionStorage.removeItem('gracie-token');setToken('');setOrders([]);let bag:Line[]=[];try{bag=JSON.parse(localStorage.getItem('gracie-bag')||'[]');}catch{bag=[];}setCart(bag);}}>Sign out</button>{!orders.length?<div className="empty"><h2>No orders to show yet</h2><p>Your orders will appear here once placed.</p></div>:orders.map(o=><button className="order-card" key={o.id} onClick={()=>{setOrder(o);setPage('order')}}><strong>{o.reference}</strong><span>{money(o.total_minor,o.currency)}</span><p>Payment: {o.payment_status} · {o.fulfilment_status||'Not confirmed'}</p><small>{new Date(o.pickup_at).toLocaleString()}</small></button>)}</>}</section>}
 {page==='about'&&<section className="about"><p className="eyebrow">{TAGLINE}</p><h1>Thoughtful bakes.<br/>Simple pleasures.</h1><p>{BRAND} offers made-to-order cakes, banana bread, bliss mini mixes and foil cake packs.</p><h2>Ordering & pickup</h2>{policy}<p>Urgent availability and rush fees require owner approval. Bulk orders need additional notice. Orders are confirmed only after verified payment.</p><h2>Contact & bakery details</h2><p>Contact details, pickup location, opening hours and the owner’s story are awaiting confirmation.</p><h2>Policies awaiting owner review</h2><p>Privacy, terms, cancellation, refund and ingredient/allergen information must be approved before live orders open. No allergen-free claims are made.</p><p>Packaging is practical and food-suitable. Specific packaging details are pending.</p></section>}
 </main><footer><div><strong>{BRAND}</strong><p>{TAGLINE}</p></div><p>Made to order. Pickup only.<br/>Demo prices and images are illustrative.</p><button onClick={()=>navigate('about')}>Contact & ordering policies</button></footer></>;
}
