import {BRAND,money} from './catalog';
export function config(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY; if(!url||!key)throw new Error('Database setup is pending. Follow SETUP.md to connect Supabase.');return {url,key};}
export type ServiceOrder=Record<string,unknown> & {id:string;approval_status:string;total_minor:number;currency:string;email:string;items:Record<string,unknown>[]};
export async function db<T=ServiceOrder>(path:string,init:RequestInit={}) {const {url,key}=config();const response=await fetch(url+'/rest/v1/'+path,{...init,headers:{apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json',...init.headers}});if(!response.ok)throw new Error('The database could not complete this request.');return (response.status===204?null:await response.json()) as T;}
export async function user(request:Request){const {url}=config();const key=process.env.SUPABASE_ANON_KEY;if(!key)throw new Error('Google sign-in setup is pending.');const authorization=request.headers.get('authorization');if(!authorization)throw new Error('Please sign in with Google.');const r=await fetch(url+'/auth/v1/user',{headers:{apikey:key,Authorization:authorization}});if(!r.ok)throw new Error('Your session expired. Please sign in again.');return r.json() as Promise<{id:string;email:string;user_metadata:{full_name:string}}>;}
export async function email(order:Record<string,unknown>,kind='confirmation') {const key=process.env.MAILGUN_API_KEY,domain=process.env.MAILGUN_DOMAIN,from=process.env.MAILGUN_FROM;if(!key||!domain||!from)return {status:'not_configured'};
 const claim=await db('rpc/claim_email',{method:'POST',body:JSON.stringify({oid:order.id,email_kind:kind})});if(!claim)return {status:'already_claimed'};
 const itemText=(order.items as {name:string;option:string;quantity:number;sell_unit:string;pieces_per_unit:number|null;preset_contents:string[]}[]||[]).map(i=>`${i.name} — ${i.option}: ${i.quantity} ${i.sell_unit}(s)${i.pieces_per_unit?' / '+i.quantity*i.pieces_per_unit+' pieces':''}${i.preset_contents.length?'\nContents: '+i.preset_contents.join(', '):''}`).join('\n');
 const form=new FormData();form.set('from',from);form.set('to',String(kind==='approval'?process.env.OWNER_NOTIFICATION_EMAIL:order.email));form.set('subject',BRAND+' — '+(kind==='approval'?'Approval requested':'Demo order confirmation'));form.set('text',BRAND+'\nReference: '+order.reference+'\n'+itemText+'\nTotal: '+money(Number(order.total_minor),String(order.currency))+'\nRequested pickup: '+order.pickup_at+'\nPickup instructions: '+order.pickup_instructions+'\nContact: '+order.contact_email+'\nDemo pricing — not final. No real payment.');
 try {const r=await fetch((process.env.MAILGUN_API_BASE||'https://api.mailgun.net')+'/v3/'+domain+'/messages',{method:'POST',headers:{Authorization:'Basic '+btoa('api:'+key)},body:form});if(!r.ok){await db('email_deliveries?order_id=eq.'+order.id+'&kind=eq.'+kind,{method:'PATCH',body:JSON.stringify({status:'failed',last_error:'Provider rejected request'})});return {status:'failed'};}const result=await r.json() as {id:string};await db('email_deliveries?order_id=eq.'+order.id+'&kind=eq.'+kind,{method:'PATCH',body:JSON.stringify({status:'sent',provider_message_id:result.id})});return {status:'sent'};}catch{try{await db('email_deliveries?order_id=eq.'+order.id+'&kind=eq.'+kind,{method:'PATCH',body:JSON.stringify({status:'unknown',last_error:'Provider outcome needs reconciliation'})});}catch{}return {status:'unknown'};}
}
